### PR TITLE
Revert laser controls dependency

### PR DESCRIPTION
**Pull request by wmurphyrd**
I have run `npm run test:machinima`, and this patch passes all machinima tests: yes

Bring all raycaster config for point mode in-house

### CODE REVIEW

**Comment by wmurphyrd** [comment]
@vincentfretin Would you do me a huge favor and see if [the pointer controls example](https://wmurphyrd.github.io/aframe-super-hands-component/examples/mouse/) works with GearVR in this build?

**Comment by vincentfretin** [comment]
I'll be able to test it tomorrow evening.

**Comment by vincentfretin** [comment]
I confirm, the ray on the ground for the left hand is back and the ray for the right hand doesn't stop at the intersection of the cube, so two issues we fixed previously with laser-controls. :-(

**Comment by vincentfretin** [comment]
For those two issues, I didn't succeed to pinpoint what laser-controls does more that progressive-controls exactly so those two issues disappear.
For the grab part, yes it works.

**Comment by wmurphyrd** [comment]
Thanks for the report! The line not shortening is an issue in A-Frame 0.7.0
`raycaster` (aren't you the author of the patch that fix that?), so that
should resolve itself. The second controller activation, on the other hand,
is something we can solve. I just failed to consider the single controller
case before, but it shouldn't be too hard.

**Comment by vincentfretin** [comment]
Yes I contributed to the patch. I'm testing with aframe master on my project too. The weird part it that with progressive-controls the ray go through the cube, and if I don't use progressive-controls and set everything myself, it stop at the intersection.

**Comment by vincentfretin** [comment]
For reference:

```
<a-entity id="cameraRig" progressive-controls="objects: .cube"/>
```

and manually:
```
        <a-entity id="cameraRig">
          <a-entity
            class="right-controller"
            laser-controls
            raycaster="objects: .cube"
            super-hands="colliderEvent: raycaster-intersection; colliderEventProperty: els; colliderEndEvent: raycaster-intersection-cleared; colliderEndEventProperty: clearedEls; colliderState:"
            static-body="shape: sphere; sphereRadius: 0.02"
          />
        </a-entity>
```

**Comment by wmurphyrd** [comment]
@vincentfretin  I was about to start pulling my hair out over the raycaster line issue, but I found it: aframevr/aframe#3170

**Comment by vincentfretin** [comment]
@wmurphyrd Bravo for finding out!

**Pull request merged**
