### PR TITLE
remove previous colliders when controls progress

### PR DESCRIPTION
**Pull request by omgitsraven**
I've done the changes necessary to remove unneeded static-body colliders once the control method they were assigned for is no longer in use... however, I'm having some trouble getting angle to build, so this is only a change to the source for now, sorry. (I've tested it locally and it seems to work fine, but for some reason `npm run dev` is just changing build.js and not the contents of the 'dist' directory...)

### CODE REVIEW

**Comment by omgitsraven** [comment]
stand by, I figured out how to build to dist...

**Comment by omgitsraven** [comment]
Scratch that! I've just been informed that pull requests for components should only change the sources anyway, so, I'm leaving it as-is after all :)

**Comment by wmurphyrd** [comment]
Thanks. Can you make your changes in semistandard js style and include unit tests for the new functionality?

**Comment by omgitsraven** [comment]
I've applied the style changes, but I'm actually not sure exactly how I'd go about writing a unit test for this change. Seems like it would require a lot of stuff taking place that it would be really hard to reproduce outside of an actual browser context...

**Comment by wmurphyrd** [comment]
Thanks. There are three levels of testing available in super-hands.
In a [unit test](https://github.com/wmurphyrd/aframe-super-hands-component/blob/master/tests/misc_components/progressive-controls.test.js), you can take a advantage of the fact that unrecognized components are treated as any other DOM text attribute and just see if `getAttribute('static-body')` returns the string "shape: sphere..." or if it returns `null`

In an [integration test](https://github.com/wmurphyrd/aframe-super-hands-component/blob/master/tests/super-hands-component/integration.test.js) you could test if the physics components are actually destroyed. 

In a [machinima test](https://github.com/wmurphyrd/aframe-super-hands-component/blob/master/machinima_tests/super_hands/progressive-controls-machinima.test.js) you can run a full browser context and replay motion-captured user input to see if the physics bodies actually stop having an impact on the scene

**Comment by wmurphyrd** [comment]
We're running into a problem in integration tests. Looks like trying to remove a physics body before it has finished initializing causes an error

**Comment by omgitsraven** [comment]
What's the workaround for that? Should I be wrapping it in a setTimeout? Or is it something that should be fixed in the physics component?

**Comment by wmurphyrd** [comment]
We should submit a fix to the physics component, but a workaround is to check if `el.body` exists. If it does, then go ahead and do the removal right away; if it doesn't, then register a callback for the `body-loaded` event on the entity to do the removal.

**Comment by omgitsraven** [comment]
Thanks for the tip! Here's a version that uses that workaround; it now passes `npm run test`. (It does NOT pass `npm run test:machinima`, but neither does `master` right now so that's hopefully not my fault.)

**Comment by wmurphyrd** [comment]
Thanks for doing this work! When I implemented the idea you gave me of using mixins for customization, it looks like it resolved this issue because I moved the physics body onto the raycasting entity which gets removed from the scene on progression.

**Pull request closed without merging**
