### PR TITLE
fix raycaster collider end event to use clearedEls property

### PR DESCRIPTION
**Pull request by vincentfretin**
Fix raycaster collider end event to use clearedEls property for compatibility with aframe master (future 0.8.0).
This fixes https://github.com/wmurphyrd/aframe-super-hands-component/issues/79

### CODE REVIEW

**Comment by wmurphyrd** [comment]
I appreciate this work. We need to keep it more flexible to take either an entity or an array because we still need to support `sphere-collider`.

**Comment by vincentfretin** [comment]
Does sphere-collider go to the first branch of the if? colliderEndEventProperty equals to empty string for sphere-collider, right?
For the failing tests, I'll look into it.

**Comment by vincentfretin** [comment]
I can do a Array.isArray check like it's done in onHit, but you're sure it's needed?

**Comment by vincentfretin** [comment]
tests are green

**Comment by vincentfretin** [comment]
I had to add babel-preset-es2015 explicitly to dev dependencies otherwise I couldn't run the tests on my machine.

**Comment by wmurphyrd** [comment]
Whoops I forgot this information existed only in my head: I've been working on `sphere-collider` (donmccurdy/aframe-extras#173) to add collision end events and I plan on deprecating `colliderState` with the next aframe-extras release. 

A side effect of accepting array or entity would also be backwards compatibility with previous A-Frame versions, right?

**Comment by vincentfretin** [comment]
No, the property was called `el` before, it is now `clearedEls`. If we want backward compatibility, we will need to check both `el` and `clearedEls` and check if it's an array.

**Comment by vincentfretin** [comment]
You may consider modifying sphere-collider to batch the hitend events, like it was done for raycaster https://github.com/aframevr/aframe/commit/cb348ec40f591f1555831e0e13d26ed83556740d
This way the property will be an array too, like raycaster.
I just read the code of sphere-collider.js, I saw in the intersect function there is a `box = new THREE.Box3()` object created for each intersection on each tick if I understand it correctly. To avoid frame drop during GC, you may want to create a box object only once and reuse the object.

**Comment by vincentfretin** [comment]
If we really want backward compatibility, we can maybe set `colliderEndEventProperty: el,clearedEls` and check for both property. But I found it ugly.
The changes to sphere-collider will break compatibility with aframe-extras too anyway.
So I think it's preferable to just say that super-hands 2.1.0 will need aframe 0.8.0 and aframe-extras 3.13.

I just rebased the branch to master. I'll let you continue on this, I I understood correctly, you probably want to remove all the stuff related to `colliderState` and depending on implementing batching for hitend events or not, add the isArray check.

**Comment by vincentfretin** [comment]
I just read the super-hands config here https://wmurphyrd.github.io/aframe-super-hands-component/examples/#physics
Is it up to date? It's currently say:
```
super-hands="colliderEvent: mouseenter;
             colliderEventProperty: intersectedEl;
             colliderState: cursor-hovered;
             grabStartButtons: mousedown;
             grabEndButtons: mouseup;
             dragDropStartButtons: mousedown;
             dragDropEndButtons: mouseup;"
```
colliderEventProperty is probably false here and should be `els` and colliderState config is not needed.

**Comment by wmurphyrd** [comment]
`super-hands` only needs to understand one end event property if we set the correct one based on the A-Frame version in `progressive-controls` gaze mode. 

Yes its ironic that just about a week after I convince Don he she change `sphere-collider` to make it more consistent with `raycaster`, they then completely change `raycaster'. 

We can't deprecate `colliderState` until `sphere-collider` gets a new release (and even then we'll wait a few version to remove the code), so that will not be part of this PR. 

I like to keep master compatible with A-Frame release so that I can put new features there for testing. So, if you don't want to finish this up with the array v. entity check in `super-hands` and the version check when setting `colliderEndEventProperty` for `progressive-controls` gaze mode, I will but it will be low on my priority list.

**Comment by vincentfretin** [comment]
Ok, in this case I'll do it, no worries.

**Comment by wmurphyrd** [comment]
OK I lied. This became priority because I want to release my `physics-collider` with the batched collision clear.

**Comment by vincentfretin** [comment]
Sorry I couldn't do the changes this weekend, I'm currently abroad for conferences. Thanks for finishing this.

For tracking purpose, https://github.com/wmurphyrd/aframe-super-hands-component/commit/3aee885a20d3029588719b78261f6ebd0d56f847 is a follow up on this PR.

**Pull request merged**
