### PR TITLE
use world position for stretchable component

### PR DESCRIPTION
**Pull request by InfiniteLee**
I have run `npm run test:machinima`, and this patch passes all machinima tests: yes

Optionally use world position for stretchable component. Optional because it is slightly more expensive to use `getWorldPosition`. This is needed, for example, for complex avatar skeletons where the "hands" that `super-hands` components are attached to aren't necessarily using the same local coordinate system.

A possible alternative that is cheaper but will run a frame behind (because not calling `updateMatrixWorld`) is:
```
this.handPos.setFromMatrixPosition(this.stretchers[0].object3D.matrixWorld)
this.otherHandPos.setFromMatrixPosition(this.stretchers[1].object3D.matrixWorld)
```

### CODE REVIEW

**Comment by wmurphyrd** [comment]
I didn't realize I hadn't switched `stretchable` to default to world position when I did the same for `grabbable`. Thanks! 

Do you need any of your contributions released in version compatible with A-Frame 0.7.1?

**Comment by wmurphyrd** [comment]
I see the pressure is on the get this merged via Mozilla/hubs#362

I've been working on a branch for A-Frame v0.8.x and finally have both unit and machinima tests passing! (Had to do a lot of work in aframe-motion-capture-components for the latter)

So, I'm very close. Sorry it's taken so long

**Comment by InfiniteLee** [comment]
That list is just for us to make sure we don’t forget. No pressure :)

**Comment by wmurphyrd** [comment]
Finally! Thanks very much for this.

**Pull request merged**
