### PR TITLE
Various adjustments

### PR DESCRIPTION
**Pull request by johnshaughnessy**
TODO: Update dist
TODO: Talk to @wmurphyrd and @infinitelee

### CODE REVIEW

**Comment by johnshaughnessy** [comment]
Kevin will break this into his smaller PR's

**Comment by wmurphyrd** [comment]
Most of the commits we're already in Kevin's other PR. I was going to shave off yours and apply them. I just finally got a release done last weekend, so I can start on these

**Comment by InfiniteLee** [comment]
This includes #124 and #129 and now #148 and #149. #129 is technically behind this, but I was going to update it with @johnshaughnessy's changes. Do you want to use the individual PR's or this combined one?

**Comment by InfiniteLee** [comment]
#150 has been added, which is the one changeset that was missing its own PR that is currently combined into this one. So this PR is comprised of: #124 #129 #148 #149 and #150

**Comment by wmurphyrd** [comment]
superseded by #150

**Pull request closed without merging**
