### PR TITLE
Make grabbing radius customizable

### PR DESCRIPTION
**Pull request by omgitsraven**
This way, if you make the physics collider on your hands larger, you can make the grabbing radius larger as well.

### CODE REVIEW

**Comment by wmurphyrd** [comment]
Between this and the physics body settings we're gonna end up with a really long list of properties if we go down this road. I'm thinking there's a way to use the `mixin` system to pass settings more concisely. 

You can also just write out the player avatar structure you want to override [as described here](https://github.com/wmurphyrd/aframe-super-hands-component#usage)
and then specify your `sphere-collider` settings in the html:

```html
<a-entity progressive-controls="objects: .myclass">
  <a-entity class="right-controller" super-hands sphere-collider="radius: 0.01"></a-entity>
  <a-entity class="left-controller" super-hands sphere-collider="radius: 0.01"></a-entity>
</a-entity>
```

**Comment by omgitsraven** [comment]
I tried that just now, and it doesn't seem to work? I'm assuming because the sphere-collider value is being overwritten by progressive-controls?

**Comment by wmurphyrd** [comment]
Hmm. It's not supposed to. That would be another bug. Would you please
share a glitch.me or create a unit test showing this?

**Comment by omgitsraven** [comment]
I'm sorry, that was my mistake just now -- I was still testing on my branch, which is where the assignment was coming from. It does seem to work after all. (I did have some weird behaviour where pressing the trigger on one hand would make both hands grab, but that might be unrelated; I'll look into it later.)

**Comment by wmurphyrd** [comment]
I just discovered that same issue with grab. It's not related to this

**Pull request closed without merging**
